using ProgrammingLanguageGUI.commands;
using ProgrammingLanguageGUI.exception;

namespace ProgrammingLanguageGUITest.tests.commands {
    /// <summary>
    /// Tests relating to the Pen class.
    /// </summary>
    [TestClass]
    public class PenTest {
        /// <summary>
        /// Tests the creation and validation of a valid Pen command. Any exception will result
        /// in a failure assertion.
        /// </summary>
        [TestMethod]
        [DataRow("blue")]
        [DataRow("BLUE")]
        [DataRow("rED")]
        public void ValidateCommandShouldSucceedWithValidArguments(string colour) {
            Pen command = new Pen(colour);

            try {
                command.ValidateCommand();
            } catch (Exception) {
                Assert.Fail();
            }
        }

        /// <summary>
        /// Tests that the ValidateCommand method throws specific exceptions and messages when a Pen object is
        /// created and validated with invalid arguments.
        /// </summary>
        [TestMethod]
        [DataRow("NOTACOLOUR", "Colour 'Notacolour' is not a valid colour.")]
        [DataRow("100", "Colour '100' is not a valid colour.")]
        public void ValidateCommandShouldThrowArgumentExceptionWithInvalidArguments(
            string argumentOne,
            string expectedExceptionMessage) {
            Pen command = new Pen(argumentOne);

            Exception ex = Assert.ThrowsException<CommandArgumentException>(() => command.ValidateCommand());

            Assert.AreEqual(expectedExceptionMessage, ex.Message);
        }

    }
}